name: Deploy to inu-dormitory-dev

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Build 단계입니다."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev'

    steps:
      - run: echo "Deploy 단계입니다."