name: Build and (conditionally) Deploy

on:
  push:
    branches:
      - '**'

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create application.yml
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_MAIN_YML }}" > ./src/main/resources/application.yml
          
      - name: Create Firebase service account key
        run: |
          mkdir -p ./src/main/resources/firebase
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 }}" | base64 --decode > ./src/main/resources/firebase/serviceAccountKey.json

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew clean build

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.MAIN_CONTAINER_NAME }}:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.MAIN_CONTAINER_NAME }}:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH to server & deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # 기존 컨테이너 중지 및 제거
            docker stop ${{ secrets.MAIN_CONTAINER_NAME }} || true
            docker rm ${{ secrets.MAIN_CONTAINER_NAME }} || true
            
            # 해당 이미지만 삭제 (다른 이미지에 영향 없음)
            docker rmi ${{ secrets.DOCKER_USERNAME }}/${{ secrets.MAIN_CONTAINER_NAME }}:latest || true
            
            # Docker 이미지 Pull
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.MAIN_CONTAINER_NAME }}:latest
            
            # Docker Volume 생성 (이미 존재하면 무시됨)
            docker volume create unidorm-images || true
            docker volume create unidorm-uploads || true
            docker volume create unidorm-logs || true
            docker volume create unidorm-main-redis-data || true

            docker network create unidorm-network || true
            docker network connect unidorm-network unidorm-main-mysql || true
            docker network connect inu-network unidorm-main-redis || true

            docker run -d --name ${{ secrets.MAIN_CONTAINER_NAME }} \
              --network unidorm-network \
              -p 8056:8080 \
              -v unidorm-images:/app/images \
              -v unidorm-uploads:/app/files \
              -v unidorm-logs:/app/logs \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/${{ secrets.MAIN_CONTAINER_NAME }}:latest